version: '2'
services:
  server:
    build: .
    command: script/start
    ports:
      - 5000:5000
    volumes:
        - .:/go/src/github.com/chrisenytc/skynet
    env_file:
      - development.env
